services:
  sqlserver2022:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "<DB_PASSWORD_REDACTED>"
    volumes:
      - sqlserver2022_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqlserver2022_data:
