name: Run CarWorkshopManager on PR

on:
  pull_request:
    paths:
      - 'CarWorkshopManager/**'

jobs:
  run-dotnet:
    name: Build and Run CarWorkshopManager
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
          install-dir: ~/.dotnet

      - name: Add .NET to PATH
        run: echo "$HOME/.dotnet" >> $GITHUB_PATH

      - name: Restore dependencies
        run: dotnet restore CarWorkshopManager

      - name: Run CarWorkshopManager
        working-directory: CarWorkshopManager
        run: dotnet run
