name: Run CarWorkshopManager on PR

on:
  pull_request:
    paths:
      - 'CarWorkshopManager/**'

jobs:
  run-dotnet:
    name: Build and Run CarWorkshopManager
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore dependencies
        run: dotnet restore CarWorkshopManager

      - name: Run CarWorkshopManager for 10 seconds (graceful stop)
        working-directory: CarWorkshopManager
        run: |
          timeout --preserve-status --signal=INT 10s dotnet run
