name: Run CarWorkshopManager on PR

on:
  pull_request:

jobs:
  run-dotnet:
    name: Build and Test CarWorkshopManager
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore dependencies
        run: dotnet restore CarWorkshopManager

      - name: Build project
        run: dotnet build CarWorkshopManager --configuration Release

      - name: Build tests
        run: dotnet build CarWorkshopManager.Tests

      - name: Run tests
        run: dotnet test CarWorkshopManager.Tests --configuration Release --no-build --verbosity normal
