name: Run CarWorkshopManager on PR

on:
  pull_request:
    paths:
      - 'CarWorkshopManager/**'

jobs:
  run-dotnet:
    name: Build and Run CarWorkshopManager
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore dependencies
        run: dotnet restore CarWorkshopManager

      - name: Build project
        run: dotnet build CarWorkshopManager --configuration Release

      - name: Run CarWorkshopManager in background
        run: |
          dotnet run --project CarWorkshopManager --configuration Release &
          echo $! > cwm_pid.txt

      - name: Wait for startup
        run: sleep 10

      - name: Stop CarWorkshopManager
        if: always()
        run: kill $(cat cwm_pid.txt) || true
