name: Run CarWorkshopManager on PR

on:
  pull_request:
    paths:
      - 'CarWorkshopManager/**'

jobs:
  run-dotnet:
    name: Build and Run CarWorkshopManager
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore dependencies
        run: dotnet restore CarWorkshopManager

      - name: Run CarWorkshopManager for 10 seconds (simulate Ctrl+C)
        working-directory: CarWorkshopManager
        run: |
          dotnet run &
          pid=$!
          sleep 10
          echo "Stopping dotnet run after 10 seconds..."
          kill -INT $pid
          wait $pid
